### ISSUE TITLE
Terminologie déroutante

### ISSUE THREAD

**Issue by bortzmeyer** [changetondns/changetondns.fr#11]
La terminologie utilisée est souvent déroutante. "Un DNS" ne veut rien dire (DNS est un protocole, pas un serveur, d'ailleurs DNS veut dire Domain Name System et pas Domain Name Server), il n'est pas précisé qu'il s'agit de changer son résolveur (pas "son DNS").

**Comment by FloX-Dev** [comment]
Je suis d'accord, mais cela ne me derange pas vraiment etant donne le public cible de ce site. D'ailleurs, si l'on voulait etre excessivement precis, on devrait dire : Serveur de resolution recursif appelant les NS hébergeant la zone DNS faisant autorité sur le domaine et répondant au protocole DNS. Je comprends et cela me dérangerait si le site était destine a des personnes averties sur le sujet (ce qui n'est clairement pas le cas). Mais pour parler a tout le monde, cela me semble parfaitement suffisant.

**Comment by Jourdelune** [comment]
Je ferme l'issue car la faute abbreviation a été réglée (Domain Name System) dans la branche dev.
