### ISSUE TITLE
🖐️Changez les Dns sur Android Tv (Box & Tv)

### ISSUE THREAD

**Issue by victore447** [changetondns/changetondns.fr#27]
![143](https://github.com/changetondns/changetondns.fr/assets/48101775/95ffb6c1-68b6-4733-8a2e-76e720fd708f)_**Bonjour,**_
De mon côté Pour Android tv (Shield tv Android, Tv Tcl Android etc..),hier j'ai testé 
**Cloudflare 1.1.1.1 & 1.0.0.1** directement sur mon interface Administration SFR de mon routeur.

![46](https://github.com/changetondns/changetondns.fr/assets/48101775/20f276f9-ac27-4004-8ee1-a7ed2136c48d)

![monmodem4](https://github.com/changetondns/changetondns.fr/assets/48101775/cf55a21d-cb49-45c1-9d58-f923f9272add)

☝️**Cela fonctionne parfaitement lors de la première manœuvre en s'inspirant de cette vidéo** 
Youtube 👉 https://youtu.be/K6rL4-NW8to (marche pas ça méthode avec SFR) pour inclure les url 
passerelle et Url DNS en statique sur paramètre IP (Protocole DHCP, Statique).

![675](https://github.com/changetondns/changetondns.fr/assets/48101775/5b4cd892-c040-43c3-8628-3867af7b752a) Par contre lorsque je redémarre le routeur SFR pour réinitialiser et 
Recommencer la manœuvre via l'interface Administration SFR, la connexion au wifi 
est refusé ensuite aux matériels (Shield tv Android, Tv Tcl Android etc..) 
en insérant les url Passerelle & Dns une seconde fois **dans paramètre IP Statique**.

☝️ **Bizarrement après être revenu sur protocole DHCP pour avoir internet via paramètre IP, environ 
une 1/2 après j'avais accès (aujourd'hui encore)  à nouveau sur tous ce qui est bloquer sur le web (sites etc..).**

![156](https://github.com/changetondns/changetondns.fr/assets/48101775/508373fb-7207-4f74-b10d-e3f4b600b581)**Votre méthode de Changez les DNS sur Android 9.0 Pie ou + marche parfaitement** sur 
Smartphones **via Cloudflare (1dot1dot1dot1.cloudflare-dns.com)** par DNS Privé en 
Sélectionnant le Nom d’hôte du fournisseur de DNS privé.

**Par contre Androit Tv n'est pas inclus dans votre site** 👉 https://changetondns.fr
☝️N'avez-vous pas une solution pour les interfaces Administration des Operateurs internet
(SFR, Orange etc..) pour Changez les DNS des Box Android tv similaire à celle de 
Android 9.0 Pie ou + (**1dot1dot1dot1.cloudflare-dns.com etc..**) via DNS Privé en 
Sélectionnant le Nom d’hôte du fournisseur de DNS privé?

**Merci pour votre réponse**.✔️

**Comment by ostix360** [comment]
Bonjour,
Si je comprends bien une fois avoir changer les dns de votre routeurs et après avoir redémarré votre routeur sfr, la box refuse la connexion à tous les appareils? 
Faites attention vous avez affiché votre adresse ip dans le screen.
Android TV n'est effectivement pas inclus dans la liste des tutos mais si vous le voulez vous pouvez venir poster des screens et la procédure pour pouvoir changer les dns sur Android TV.

**Comment by ostix360** [comment]
Il est quand même conseillé de mettre les dns secondaire également.
Tel que vous me le décrivez vous avez en faite changer le serveur DNS par défaut de votre box.
Si vous fournissez suffisamment de screen on pourra bien sur rajouter le routeur sfr dans la liste des tutoriels

**Comment by victore447** [comment]
Quand vous parlez de screen c'est des captures d'écrans ?

Si c'est de ça que il s'agit,que voulez vous d'autre en capture d'écran (Je masquerai mon IP).

**Comment by ostix360** [comment]
oui pour aider les autres dans la manipulation. 
Ce serait parfait!

**Comment by victore447** [comment]
Quoi exactement?
La première image de mon premier message sans mon adresse Ip etc..?

**Comment by ostix360** [comment]
Globalement l'ensemble des pages que vous emprunté pour pouvoir changer les dns du navigateur avec l'adresse ip de la box dans la barre d'adresse à l'image de votre premier message.

**Comment by ostix360** [comment]
Merci pour votre contribution le site va être mis à jour dans quelques instants

**Comment by victore447** [comment]
![155](https://github.com/changetondns/changetondns.fr/assets/48101775/4c37b58b-8524-47bd-83b7-a94778488a18)  Ok Je vous Laisse ✔️
