### ISSUE TITLE
Add dns servers from dns0.eu

### ISSUE THREAD

**Issue by yilas** [changetondns/changetondns.fr#6]
As described in [dns0.eu](https://www.dns0.eu/) website :  

> dns0.eu est une association française à but non lucratif fondée en 2022 par [Romain Cointepas](https://twitter.com/RomainCointepas) et [Olivier Poitrey](https://twitter.com/Olivier_Poitrey), co-fondateurs de [NextDNS](https://nextdns.io/).

It might be a good idea to suggest these servers ?

List of ipv4 and ipv6 dns servers : 

```bash
[Resolve]
DNS=193.110.81.0#dns0.eu
DNS=2a0f:fc80::#dns0.eu
DNS=185.253.5.0#dns0.eu
DNS=2a0f:fc81::#dns0.eu
DNSOverTLS=yes
```

**Comment by ostix360** [comment]
And as hostname for android device `dns0.eu`

**Comment by matrixbx** [comment]
dns0.eu fourni plusieurs services plus ou moins menteurs !
https://www.dns0.eu/fr
https://www.dns0.eu/fr/zero
https://www.dns0.eu/fr/kids

Et un à priori "neutre" (DoT,DoH,DoQ)
https://www.dns0.eu/fr/open

**Comment by ostix360** [comment]
Done
